pub mod codec;
pub mod concurrency;
pub mod coordination;
pub mod factory;
pub mod job;
pub mod job_attempt;
pub mod job_store_shard;
pub mod keys;
pub mod retry;
pub mod settings;
pub mod shard_guard;
pub mod storage;
pub mod task_broker;
pub mod trace;
pub use silo_macros::test;
pub mod pb {
    // Generated by prost/tonic into OUT_DIR (per prost-build best practice)
    include!(concat!(env!("OUT_DIR"), "/silo.v1.rs"));
}
pub mod server;
