pub mod factory;
pub mod job_store_shard;
pub mod keys;
pub mod retry;
pub mod settings;
pub mod storage;
pub mod pb {
    // Generated by prost/tonic into OUT_DIR (per prost-build best practice)
    include!(concat!(env!("OUT_DIR"), "/silo.v1.rs"));
}
pub mod server;
