pub mod arrow_ipc;
pub mod cluster_client;
pub mod cluster_query;
pub mod codec;
pub mod concurrency;
pub mod coordination;
pub mod dst_events;
pub mod factory;
pub mod gubernator;
pub mod job;
pub mod job_attempt;
pub mod job_store_shard;
pub mod keys;
pub mod metrics;
pub mod query;
pub mod retry;
pub mod routing_client;
pub mod settings;
pub mod shard_range;
pub mod storage;
pub mod task;
pub mod task_broker;
pub mod trace;
#[cfg(feature = "dst")]
pub mod turmoil_object_store;
pub mod webui;
pub use silo_macros::test;
pub mod fb {
    // Generated by flatc into OUT_DIR from schema/internal_storage.fbs
    #![allow(unused_imports, clippy::all, dead_code, unsafe_op_in_unsafe_fn)]
    include!(concat!(env!("OUT_DIR"), "/internal_storage_generated.rs"));
}
pub mod pb {
    // Generated by prost/tonic into OUT_DIR (per prost-build best practice)
    include!(concat!(env!("OUT_DIR"), "/silo.v1.rs"));

    // Gubernator proto definitions for rate limit client
    pub mod gubernator {
        include!(concat!(env!("OUT_DIR"), "/pb.gubernator.rs"));
    }
}
pub mod server;
pub mod siloctl;

/// Default scan options for all silo scans.
///
/// SlateDB defaults `cache_blocks` to `false` for scans to avoid cache pollution
/// from large sequential reads. However, silo's scans are repeated, short-range
/// prefix scans over the same SSTs, so caching SST indexes (and data blocks) is
/// critical — without it, every scan re-parses the full flatbuffer SST index,
/// which dominates CPU under load.
pub fn scan_options() -> slatedb::config::ScanOptions {
    slatedb::config::ScanOptions::default().with_cache_blocks(true)
}
