name: "Setup test environment"
description: ""
inputs:
  cachix_auth_token:
    description: "Cachix auth token"
    required: true
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: nixbuild/nix-quick-install-action@v30
    - name: Cachix setup
      uses: cachix/cachix-action@v16
      with:
        name: silo
        authToken: "${{ inputs.cachix_auth_token }}"
    - name: Restore and save Nix store
      uses: nix-community/cache-nix-action@v6
      with:
        # Include Cargo.lock since Nix builds depend on Rust dependencies
        # Include runner.arch to separate x86 and ARM64 caches (they have different store paths)
        # Include github.run_id to ensure new caches are always saved (GH caches are immutable)
        primary-key: nix-v2-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock', '**/Cargo.lock') }}-${{ github.run_id }}
        restore-prefixes-first-match: nix-v2-${{ runner.os }}-${{ runner.arch }}-
        # Garbage collect to keep cache size manageable
        gc-max-store-size-linux: 4294967296
        # Save cache even if job fails (to cache partial builds)
        save-always: true
    - run: |
        set -eo pipefail

        # Write dev env to a file first so nix failures are caught by set -e
        # (process substitution with source swallows the exit code)
        nix print-dev-env --show-trace > /tmp/nix-dev-env.sh
        source /tmp/nix-dev-env.sh

        output_file="nix-env.txt"

        # Clear the output file
        > $output_file

        # Loop over each variable in the environment
        while IFS='=' read -r -d '' name value; do
            # Skip if the variable is a function or read-only or non-alphanumeric
            [[ "$(declare -p $name)" =~ "declare -[a-z]*r[a-z]* " ]] && continue
            [[ ! $name =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]] && continue

            # Check if the variable value contains a newline
            if [[ "$value" != *$'\n'* ]]; then
                # It doesn't, so write the variable and its value (stripping quotes) to the file
                echo "${name}=${value//\"/}" >> $output_file
            fi
        done < <(env -0)

        # useful for debugging what env is exported
        # cat nix-env.txt
      shell: bash

    - run: cat nix-env.txt >> "$GITHUB_ENV"
      shell: bash
